INSERT INTO MATERIAL VALUES('1', 'Material 001', 'S');
INSERT INTO MATERIAL VALUES('2', 'Material 002', 'N');
INSERT INTO MATERIAL VALUES('3', 'Material 003', 'S');
INSERT INTO MATERIAL VALUES('4', 'Material 004', 'N');